name: child workflow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string 
      app:
        required: true
        type: string
    outputs:
      child_output:
        value: ${{ jobs.demojob.outputs.demo }}

jobs:
  demojob:
    runs-on: ubuntu-latest
    outputs:
      demo: ${{ steps.step1.outputs.demo1 }}
    steps:
      - name: chekout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set up Maven
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: produce output
        id: step1
        run: |
          echo "demo1=environment is ${{ inputs.env }}" >> $GITHUB_OUTPUT  

      # - name: cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.m2/repository
      #     key: ${{ runner.os }}-maven-${{ hashFiles('kalingachainofcafe/pom.xml') }}

      # - name: maven clean
      #   run: |
      #     cd ${{ github.workspace }}/kalingachainofcafe
      #     mvn clean install

      - name: print env
        run: |
          echo "${{ inputs.env }}"

      - name: print child output
        run: echo "${{ steps.step1.outputs.demo1 }}"